apiVersion: v1
kind: Service
metadata:
  name: tristan-benavides-backend-api-load-balancer-service
spec:
  type: LoadBalancer
  loadBalancerIP: 35.192.34.27
  selector:
    app: tristan-benavides-backend-api-app
  ports:
  - port: 80
    targetPort: 8080
