name: Deploy
on:
  push:
    branches: [master]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    
    - name: Setup GCloud CLI
      uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        project_id: ${{ secrets.GCP_PROJECT }}
        service_account_key: ${{ secrets.GCP_CREDENTIALS }}
        export_default_credentials: true
    
    - name: Install Google Cloud SDK components
      run: yes | gcloud components install beta app-engine-go
      
    - name: Configure Docker
      run: gcloud auth configure-docker
    
    - name: Build and Publish Docker Image
      run: |
        gcloud config set project ${{ secrets.GCP_PROJECT }}
        docker build -t gcr.io/tristan-benavides-website/backend-api:latest --build-arg SENDGRID_API_KEY=${{ secrets.SENDGRID_API_KEY }} .
        docker image push gcr.io/tristan-benavides-website/backend-api

    - name: Create GKE Cluster
      run: chmod +rx create_gke_cluster.sh && ./create_gke_cluster.sh -c tristan-benavides-backend-api-gke -n 1 --z us-central1
    
    - name: Deploy Kubernetes Deployment
      run: kubectl apply -f deployment.yaml
    
    - name: Deploy Kubernetes Load Balancer Service
      run: kubectl apply -f service.yaml